services:
  gameoflifeapi:
    image: ${DOCKER_REGISTRY-}gameoflifeapi
    build:
      context: .
      dockerfile: GameOfLifeApi/Dockerfile
    depends_on: 
      - database
    ports:
      - "5000:80"
    restart: always
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development
  database:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - "3306:3306"
    expose: 
      - 3306
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: juh49kjh
      MYSQL_USER: josh
      MYSQL_PASSWORD: juh49kjh
      MYSQL_DATABASE: gameoflifedb
volumes:
  db-volume: